### PR TITLE
Minor fixes, better support for yai & yo

### PR DESCRIPTION
**Pull request by jlnr**
Thanks for this sweet little library. I've been using Ting for converting text from Hanyu Pinyin to Bopomofo, and it works like a charm except for 唉唷, where the latter character raises an exception somewhere in conversions.rb.

After digging around for a bit, it turns out that this syllable is simply missing from final.csv. While looking at the table, I've noticed that the Bopomofo for yai is missing as well, as well as the Wade-Giles romanization for these two syllables.

I've added these syllables while double-checking with these sources:
* moedict.tw for the correct Zhuyin for yo/yai
* [http://www.eastasianlib.org/ctp/RomTable/Chipinyintowade.pdf](A PDF from eastasianlib.org) for the Wade-Giles romanization of "yai"
* [https://libraries.indiana.edu/chinese-studies-pinyin-wade-giles-conversion-table](This website from Indiana University Bloomington) for the Wade-Giles romanization of "yo"

I also cleaned up some warnings and typos on my way.

### CODE REVIEW

**Comment by jlnr** [comment]
I've disabled the Ruby 1.9.3 build on Travis as this version has been unsupported since 2015. Not quite sure what to do about rbx, as I'm not familiar with it at all 😕

**Comment by plexus** [comment]
Hi Julian, this is great! I'm so happy someone is getting some use out of this. This was the first Ruby library I released, over ten years ago. I haven't looked at it in a while but yay for the power of open source :)

I'll drop rbx from the Travis matrix, I have no interest in making an effort to stay compatible with Rubinius. I'll add some newer Ruby versions while I'm at it.

**Comment by plexus** [comment]
Released as 0.10.0.

thankyou

**Comment by jlnr** [comment]
np!

I actually just discovered another small thing. PR incoming...

**Comment by plexus** [comment]
Cool. Jruby is error-ing on travis, seems it's having trouble installing it... the tests seem fine when I run them on JRuby locally. 

Contrary to Rubinius I would like to stay compatible with JRuby, that's usually also not a lot of effort. Not sure what's up with Travis, suggestions welcoming. Maybe we should pin jruby to a specific version to test with.

**Pull request merged**
